using System;
using System.Collections.Generic;
using BansheeGz.BGDatabase;

//=============================================================
//||                   Generated by BansheeGz Code Generator ||
//=============================================================

#pragma warning disable 414

public partial class DB_Ranking : BGEntity
{

	public class Factory : BGEntity.EntityFactory
	{
		public BGEntity NewEntity(BGMetaEntity meta) => new DB_Ranking(meta);
		public BGEntity NewEntity(BGMetaEntity meta, BGId id) => new DB_Ranking(meta, id);
	}
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ?? (_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(5345270884850775532UL,13891974603220060554UL), () => _metaDefault = null));
	public static BansheeGz.BGDatabase.BGRepoEvents Events => BGRepo.I.Events;
	public static int CountEntities => MetaDefault.CountEntities;
	public System.String name
	{
		get => _name[Index];
		set => _name[Index] = value;
	}
	public System.Int32 score
	{
		get => _score[Index];
		set => _score[Index] = value;
	}
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName _name => _ufle12jhs77_name ?? (_ufle12jhs77_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(4938304394093654301UL, 2561471781619879304UL), () => _ufle12jhs77_name = null));
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_score;
	public static BansheeGz.BGDatabase.BGFieldInt _score => _ufle12jhs77_score ?? (_ufle12jhs77_score = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(5620213307959542913UL, 14160160638331178117UL), () => _ufle12jhs77_score = null));
	private static readonly DB_Ranking.Factory _factory0_PFS = new DB_Ranking.Factory();
	private DB_Ranking() : base(MetaDefault)
	{
	}
	private DB_Ranking(BGId id) : base(MetaDefault, id)
	{
	}
	private DB_Ranking(BGMetaEntity meta) : base(meta)
	{
	}
	private DB_Ranking(BGMetaEntity meta, BGId id) : base(meta, id)
	{
	}
	public static DB_Ranking FindEntity(Predicate<DB_Ranking> filter)
	{
		return (DB_Ranking) MetaDefault.FindEntity(entity => filter==null || filter((DB_Ranking) entity));
	}
	public static List<DB_Ranking> FindEntities(Predicate<DB_Ranking> filter, List<DB_Ranking> result=null, Comparison<DB_Ranking> sort=null) => BGCodeGenUtils.FindEntities(MetaDefault, filter, result, sort);
	public static void ForEachEntity(Action<DB_Ranking> action, Predicate<DB_Ranking> filter=null, Comparison<DB_Ranking> sort=null)
	{
		MetaDefault.ForEachEntity(entity => action((DB_Ranking) entity), filter == null ? null : (Predicate<BGEntity>) (entity => filter((DB_Ranking) entity)), sort==null?(Comparison<BGEntity>) null:(e1,e2) => sort((DB_Ranking)e1,(DB_Ranking)e2));
	}
	public static DB_Ranking GetEntity(BGId entityId) => (DB_Ranking) MetaDefault.GetEntity(entityId);
	public static DB_Ranking GetEntity(int index) => (DB_Ranking) MetaDefault[index];
	public static DB_Ranking GetEntity(string entityName) => (DB_Ranking) MetaDefault.GetEntity(entityName);
	public static DB_Ranking NewEntity() => (DB_Ranking) MetaDefault.NewEntity();
	public static DB_Ranking NewEntity(BGId entityId) => (DB_Ranking) MetaDefault.NewEntity(entityId);
	public static DB_Ranking NewEntity(Action<DB_Ranking> callback)
	{
		return (DB_Ranking) MetaDefault.NewEntity(new BGMetaEntity.NewEntityContext(entity => callback((DB_Ranking)entity)));
	}
}
#pragma warning restore 414
